### ISSUE TITLE
Custom Editor

### ISSUE THREAD

**Issue by ddankwerth** [recogito/recogito-client-core#19]
I used the "old" version of annotorious and adjusted the editor as the examples.
I am trying to use the new version and like it a lot, i think its a massive step forward ,however, I understand the customizsation of the editor is done using this package and i couldnt figure out for the wiki how to do it, not if its possible without react.
my environment is angular and i am using the prebuilt annotorious.
please advise if the wiki can be extended or if an examples directory can be added

thanks

**Comment by rsimon** [comment]
The new editor popup is a React component. I assume it would be possible to plug new widgets in that are not React, but I haven't yet explored how that can be done.

Right now, your only possibility would be to fork Annotorious, build your own React widgets, and insert them in `index.js`, instead of the default widgets:

https://github.com/recogito/annotorious/blob/master/src/index.js#L65-L66

Documentation isn't done yet, I'm afraid; nor is it possible to inject components through the API, without forking the project. It's all on my wishlist, but I can't say when I get around to doing that.

Let me know if you make an attempt at this and/or if you know how to insert non-React components into the Editor. I'm really interested in any insights or notes you might have - which might help move the project (and documentation) further in this regard.

**Comment by rsimon** [comment]
Also linking https://github.com/recogito/annotorious/issues/5 for reference, since this is essentially looking for a way to insert a simplified (or, in any case, completely custom) popup instead of the full-blown React component.

**Comment by rsimon** [comment]
P.S. out of curiosity: in the old Annotorious, did you replace the editor/popup completely? Or add new fields to it?

**Comment by ddankwerth** [comment]
Added fields ... It worked really well and was really simple


בתאריך יום א׳, 17 במאי 2020, 16:31, מאת Rainer Simon ‏<
notifications@github.com>:

**Comment by rsimon** [comment]
I could imagine some sort of basic "field plugin" API, along the lines of the old Annotorious. Essentially you would hand Annotorious one or more vanilla JS functions on init. These functions would take an object as argument:

```json 
{
   annotation:
   onUpdateBody:
   onAddBody:
   onRemoveBody
}
```

The `on...` Arguments would be callbacks for the plugin function to modify the annotation contents. As a return value, the function would be supposed to return a DOM node, i.e. the element to insert into the editor. 

A function like that could be easily wrapped for React internally. Would something like this work?

**Comment by RodolfoPena** [comment]
How to hide the comment and tags editor? I want to create an annotation only by making a rectangle.

**Comment by rsimon** [comment]
Assuming this is question is for the standard Annotorious version (not the OpenSeadragon) plugin: the `headless` init config option is what you are looking for:

https://recogito.github.io/annotorious/api-docs/annotorious/

(The option is not yet available in OpenSeadragon. But will come as soon as I find the time.)

**Comment by RodolfoPena** [comment]
@rsimon , thank you very much for your answer. But now, I can't save any annotation. There is any aditional option to fire the createAnnotation functionality? Thanks in advance

**Comment by rsimon** [comment]
Annotations need to have a body, otherwise they are discarded immediately. (Same behavior as with the popup, when you hit OK on an empty annotation.) 

Therefore, in headless mode, you need to set a body via `.applyTemplate`. If you don‘t care about the contents of the body, and are just interested in the box coordinates, any dummy body will do. E.g. something like:

```js
anno.applyTemplate({
  "type": "TextualBody",
  "purpose": "tagging",
  "value": "Highlight"
});
```

That will just add a dummy tag ("Highlight") to the annotation, thus ensuring that it gets created.

**Comment by rsimon** [comment]
Just a quick heads-up: I started working on a plugin API that allows adding new components to the editor and/or removing the original comment and tag widget. A first version might become available in the next release. But documentation will (probably) be lacking of a while to come. Let me know if you want to try this out in advance. More info here:

https://github.com/recogito/annotorious/issues/43#issuecomment-691026876
https://gist.github.com/rsimon/7acd0929b44ac52a5affcf289fd0aacd
https://twitter.com/aboutgeo/status/1304355124421300230?s=20

**Comment by rsimon** [comment]
It's now possible to extend the editor with your own components, just like in the old Annotorious version. The feature is available in the latest relase (beta...) and documentation for this is here:

https://recogito.github.io/guides/extending-the-editor/
